[tool.flakehell]
max_line_length = 120
show_source = true
extended_default_ignore=[]

[tool.flakehell.plugins]
flake8-annotations=["+*"]
flake8-bugbear=["+*"]
flake8-builtins=["+*"]
flake8-comprehensions=["+*"]
flake8-coding=["+*", "-C101"]
flake8-django=["+*"]
flake8-docstrings=["+*", "-D100", "-D400"]
flake8-debugger=["+*"]
flake8-eradicate=["+*"]
flake8-expression-complexity=["+*"]
flake8-functions=["+*"]
flake8-import-order=["+*"]
flake8-multiline-containers=["+*"]
flake8-polyfill=["+*"]
flake8-plugin-utils=["+*"]
flake8-print=["+*"]
flake8-logging-format=["+*"]
flake8-quotes=["+*"]
flake8-return=["+*"]
flake8-simplify=["+*"]
flake8-string-format=["+*"]
flake8-scrapy=["+*"]
