# Generated by Django 2.2.17 on 2021-12-19 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('slug', models.CharField(editable=False, max_length=200)),
                ('description', models.TextField(max_length=1000, verbose_name='Описание задачи')),
                ('task_text', models.TextField(max_length=50000, verbose_name='Текст задания в формате markdown/html')),
                ('text_code_of_testing', models.TextField(max_length=50000, verbose_name='Текст кода теста для проверки решения (в формате Python)')),
                ('text_code_of_example', models.TextField(max_length=50000, verbose_name='Текст кода примера, который будет выведен как патерн выполнения задачи')),
                ('timeout_running_container', models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='Таймаут для запуска контейнера')),
                ('timeout_refresh_result', models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='Таймаут на получение результата проверки')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('slug', models.CharField(editable=False, max_length=200)),
                ('description', models.TextField(max_length=1000, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория заданий',
                'verbose_name_plural': 'Категории заданий',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserRunTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('job_id', models.UUIDField(editable=False, verbose_name='Идентификатор задачи')),
                ('code', models.TextField(max_length=50000, verbose_name='Код пользователя')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codexrunner.Task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codexrunner.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код решения задачи',
                'verbose_name_plural': 'Код решения задач',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codexrunner.TaskCategory', verbose_name='Категория'),
        ),
    ]
