# Generated by Django 2.2.17 on 2021-11-28 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('slug', models.CharField(editable=False, max_length=200)),
            ],
            options={
                'verbose_name': 'Категория заданий',
                'verbose_name_plural': 'Категории заданий',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('slug', models.CharField(editable=False, max_length=200)),
                ('task_text', models.TextField(max_length=50000, verbose_name='Текст задания в формате markdown/html')),
                ('text_code_of_testing', models.TextField(max_length=50000, verbose_name='Текст кода теста для проверки решения (в формате Python)')),
                ('text_code_of_example', models.TextField(max_length=50000, verbose_name='Текст кода примера, который будет выведен как патерн выполнения задачи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codexrunner.TaskCategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
